"""added users.idempotency_key, and users.blocked_reason

Revision ID: 6314522737de
Revises: afb2cdef008f
Create Date: 2024-09-10 20:25:22.804186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6314522737de'
down_revision: Union[str, None] = 'afb2cdef008f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('idempotency_key', sa.String(), nullable=False))
    op.add_column('users', sa.Column('blocked_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_reason')
    op.drop_column('users', 'idempotency_key')
    # ### end Alembic commands ###
