"""added users.lockout_expires_at, users.is_blocked, users.is_active. and users.password

Revision ID: afb2cdef008f
Revises: da68123e9692
Create Date: 2024-09-09 11:06:20.812579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb2cdef008f'
down_revision: Union[str, None] = 'da68123e9692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('lockout_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lockout_expires_at')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
